const fetch = require('node-fetch');
const express = require('express');
const fs = require('fs');

const app = express();
const port = 5000;

const paths = [];

const downloadFile = (async (url, path) => {
  if (fs.existsSync(path) || paths.filter(e => e === path).length > 0) {
    return;
  }
  paths.push(path);
  console.log('updating ' + path);
  fetch(url)
    .then(x => x.arrayBuffer())
    .then(x => fs.writeFileSync(path, Buffer.from(x)));
});

const allFood = [];

const resources = {
  'Wheat Flour': { res: 'gfx/invobjs/flour-wheatflour' },
  'Barley Flour': { res: 'gfx/invobjs/flour-barleyflour' },
  'Millet Flour': { res: 'gfx/invobjs/flour-milletflour' },
  'Laurel Leaves': { res: 'gfx/invobjs/leaf-laurel' },
  'Chicken Egg': { res: 'gfx/invobjs/egg-chicken' },
  'Lettuce Leaf': { res: 'gfx/invobjs/lettuceleaf' },
  'Chives': { res: 'gfx/invobjs/herbs/chives' },
  'Yellow Onion': { res: 'gfx/invobjs/yellowonion' },
  'Kvann': { res: 'gfx/invobjs/herbs/kvann' },
  'Red Onion': { res: 'gfx/invobjs/redonion' },
  'Beetroot Leaves': { res: 'gfx/invobjs/beetleaves' },
  'Chantrelles': { res: 'gfx/invobjs/herbs/chantrelle' },
  'Beetroot': { res: 'gfx/invobjs/beet' },
  'Carrot': { res: 'gfx/invobjs/carrot' },
  'Yellowfeet': { res: 'gfx/invobjs/herbs/yellowfoot' },
  'Turnip': { res: 'gfx/invobjs/turnip' },
  'Snowtop': { res: 'gfx/invobjs/herbs/snowtop' },
  'Green Kelp': { res: 'gfx/invobjs/herbs/greenkelp' },
  'Giant Puffball': { res: 'gfx/invobjs/herbs/giantpuffball' },
  'Block of Trombone Chantrelle': { res: 'gfx/invobjs/wblock-trombonechantrelle' },
  'Bay Bolete': { res: 'gfx/invobjs/herbs/baybolete' },
  'Mulberry': { res: 'gfx/invobjs/mulberry' },
  'Parasol Mushroom': { res: 'gfx/invobjs/herbs/parasolshroom' },
  'Blueberries': { res: 'gfx/invobjs/herbs/blueberry' },
  'Troll Mushrooms': { res: 'gfx/invobjs/trollshrooms' },
  'Elderberries': { res: 'gfx/invobjs/seed-elderberrybush' },
  'Parboiled Morels': { res: 'gfx/invobjs/lorchelwet' },
  'Cavebulb': { res: 'gfx/invobjs/herbs/cavebulb' },
  'Raspberry': { res: 'gfx/invobjs/seed-raspberrybush' },
  'Blackcurrant': { res: 'gfx/invobjs/seed-blackcurrant' },
  'Cherries': { res: 'gfx/invobjs/cherry' },
  'Redcurrant': { res: 'gfx/invobjs/seed-redcurrant' },
  'Bloated Bolete': { res: 'gfx/invobjs/herbs/bloatedbolete' },
  'Blackberry': { res: 'gfx/invobjs/seed-blackberrybush' },
  'Lingonberries': { res: 'gfx/invobjs/herbs/lingon' },
  'Magpie (Pie)': { res: 'gfx/invobjs/magpiepie' },
  'Ruby Bolete': { res: 'gfx/invobjs/herbs/rubybolete' },
  'Seaberries': { res: 'gfx/invobjs/seed-sandthorn' },
  'Dried Morels': { res: 'gfx/invobjs/lorcheldried' },
  'Sloan Berries': { res: 'gfx/invobjs/seed-blackthorn' },
  'Dog Rose Hips': { res: 'gfx/invobjs/seed-dogrose' },
  'Gooseberry': { res: 'gfx/invobjs/seed-gooseberrybush' },
  'Grapes': { res: 'gfx/invobjs/grapes' },
  'Black Trumpets': { res: 'gfx/invobjs/herbs/blacktrumpet' },
  'Field Blewits': { res: 'gfx/invobjs/herbs/fieldblewit' },
  'Dusk Fern': { res: 'gfx/invobjs/herbs/duskfern' },
  'Red Apple': { res: 'gfx/invobjs/apple' },
  'Marsh-Mallow': { res: 'gfx/invobjs/herbs/marshmallow' },
  'Plum': { res: 'gfx/invobjs/plum' },
  'Strawberries': { res: 'gfx/invobjs/herbs/strawberry' },
  'Lemon': { res: 'gfx/invobjs/lemon' },
  'Pear': { res: 'gfx/invobjs/pear' },
  'Wood Strawberry': { res: 'gfx/invobjs/woodstrawberry' },
  'Persimmon': { res: 'gfx/invobjs/persimmon' },
  'Quince': { res: 'gfx/invobjs/quince' },
  'Sorb Apple': { res: 'gfx/invobjs/sorbapple' },
  'Medlar': { res: 'gfx/invobjs/medlar' },
  'Candleberry': { res: 'gfx/invobjs/herbs/candleberry' },
  'Indigo Cap': { res: 'gfx/invobjs/herbs/indigocap' },
  'Black Pepper': { res: 'gfx/invobjs/pepper' },
  'Dill': { res: 'gfx/invobjs/herbs/dill' },
  'Juniper Berries': { res: 'gfx/invobjs/seed-juniper' },
  'Leek': { res: 'gfx/invobjs/leek' },
  'Magpie Egg': { res: 'gfx/invobjs/egg-magpie' },
  'Sage': { res: 'gfx/invobjs/herbs/salvia' },
  'Thyme': { res: 'gfx/invobjs/herbs/thyme' },
  'Domestic Honey': { res: 'gfx/invobjs/honey' },
  'Stinging Nettle': { res: 'gfx/invobjs/herbs/stingingnettle' },
  'Apple tree': { res: 'gfx/invobjs/wblock-appletree' },
  'Cave Lantern': { res: 'gfx/invobjs/herbs/cavelantern' },

  'Adder': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-adder' },
  'Badger': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-badger' },
  'Bat': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-bat' },
  'Bear': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-bear' },
  'Beaver': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-beaver' },
  'Beef': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-cow' },
  'Boar': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-boar' },
  'Bog turtle': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-bogturtle' },
  'Cachalot': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-spermwhale' },
  'Caverat': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-caverat' },
  'Fox': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-fox' },
  'Goat': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-goat' },
  'Grey Seal': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-greyseal' },
  'Hedgehog': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-hedgehog' },
  'Horse': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-horse' },
  'Lynx': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-lynx' },
  'Mammoth': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-mammoth' },
  'Mole': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-mole' },
  'Moose': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-moose' },
  'Mutton': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-sheep' },
  'Orca': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-orca' },
  'Otter': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-otter' },
  'Pork': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-pig' },
  'Rabbit': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-rabbit' },
  'Reindeer Venison': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-reindeer' },
  'Squirrel': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-squirrel' },
  'Stoat': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-stoat' },
  'Venison': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-reddeer' },
  'Walrus': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-walrus' },
  'Wild Beef': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-aurochs' },
  'Wild Horse': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-wildhorse' },
  'Wild Mutton': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-wildgoat' },
  'Wildgoat': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-wildgoat' },// ????
  'Wolf': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-wolf' },
  'Wolverine': { res: 'gfx/invobjs/meat-raw', mod: 'gfx/invobjs/meat-wolverine' },

  'Smoked Adder': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-adder' },
  'Smoked Badger': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-badger' },
  'Smoked Bat': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-bat' },
  'Smoked Bear': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-bear' },
  'Smoked Beaver': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-beaver' },
  'Smoked Beef': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-cow' },
  'Smoked Boar': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-boar' },
  'Smoked Bog turtle': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-bogturtle' },
  'Smoked Cachalot': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-spermwhale' },
  'Smoked Caverat': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-caverat' },
  'Smoked Fox': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-fox' },
  'Smoked Goat': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-goat' },
  'Smoked Grey Seal': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-greyseal' },
  'Smoked Hedgehog': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-hedgehog' },
  'Smoked Horse': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-horse' },
  'Smoked Lynx': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-lynx' },
  'Smoked Mammoth': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-mammoth' },
  'Smoked Mole': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-mole' },
  'Smoked Moose': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-moose' },
  'Smoked Mutton': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-sheep' },
  'Smoked Orca': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-orca' },
  'Smoked Otter': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-otter' },
  'Smoked Pork': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-pig' },
  'Smoked Rabbit': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-rabbit' },
  'Smoked Reindeer Venison': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-reindeer' },
  'Smoked Squirrel': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-squirrel' },
  'Smoked Stoat': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-stoat' },
  'Smoked Venison': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-reddeer' },
  'Smoked Walrus': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-walrus' },
  'Smoked Wild Beef': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-aurochs' },
  'Smoked Wild Horse': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-wildhorse' },
  'Smoked Wild Mutton': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-wildgoat' },
  'Smoked Wildgoat': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-wildgoat' },// ????
  'Smoked Wolf': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-wolf' },
  'Smoked Wolverine': { res: 'gfx/invobjs/meat-smoked', mod: 'gfx/invobjs/meat-wolverine' },

  'Roast Adder': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-adder' },
  'Roast Badger': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-badger' },
  'Roast Bat': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-bat' },
  'Roast Bear': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-bear' },
  'Roast Beaver': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-beaver' },
  'Roast Beef': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-cow' },
  'Roast Boar': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-boar' },
  'Roast Bog turtle': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-bogturtle' },
  'Roast Cachalot': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-spermwhale' },
  'Roast Caverat': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-caverat' },
  'Roast Fox': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-fox' },
  'Roast Goat': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-goat' },
  'Roast Grey Seal': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-greyseal' },
  'Roast Hedgehog': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-hedgehog' },
  'Roast Horse': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-horse' },
  'Roast Lynx': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-lynx' },
  'Roast Mammoth': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-mammoth' },
  'Roast Mole': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-mole' },
  'Roast Moose': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-moose' },
  'Roast Mutton': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-sheep' },
  'Roast Orca': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-orca' },
  'Roast Otter': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-otter' },
  'Roast Pork': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-pig' },
  'Roast Rabbit': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-rabbit' },
  'Roast Reindeer Venison': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-reindeer' },
  'Roast Squirrel': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-squirrel' },
  'Roast Stoat': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-stoat' },
  'Roast Venison': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-reddeer' },
  'Roast Walrus': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-walrus' },
  'Roast Wild Beef': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-aurochs' },
  'Roast Wild Horse': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-wildhorse' },
  'Roast Wild Mutton': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-wildgoat' },
  'Roast Wildgoat': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-wildgoat' },// ????
  'Roast Wolf': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-wolf' },
  'Roast Wolverine': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-wolverine' },

  'Sizzling Roast Adder': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-adder' },
  'Sizzling Roast Badger': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-badger' },
  'Sizzling Roast Bat': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-bat' },
  'Sizzling Roast Bear': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-bear' },
  'Sizzling Roast Beaver': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-beaver' },
  'Sizzling Roast Beef': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-cow' },
  'Sizzling Roast Boar': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-boar' },
  'Sizzling Roast Bog turtle': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-bogturtle' },
  'Sizzling Roast Cachalot': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-spermwhale' },
  'Sizzling Roast Caverat': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-caverat' },
  'Sizzling Roast Fox': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-fox' },
  'Sizzling Roast Goat': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-goat' },
  'Sizzling Roast Grey Seal': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-greyseal' },
  'Sizzling Roast Hedgehog': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-hedgehog' },
  'Sizzling Roast Horse': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-horse' },
  'Sizzling Roast Lynx': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-lynx' },
  'Sizzling Roast Mammoth': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-mammoth' },
  'Sizzling Roast Mole': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-mole' },
  'Sizzling Roast Moose': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-moose' },
  'Sizzling Roast Mutton': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-sheep' },
  'Sizzling Roast Orca': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-orca' },
  'Sizzling Roast Otter': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-otter' },
  'Sizzling Roast Pork': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-pig' },
  'Sizzling Roast Rabbit': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-rabbit' },
  'Sizzling Roast Reindeer Venison': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-reindeer' },
  'Sizzling Roast Squirrel': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-squirrel' },
  'Sizzling Roast Stoat': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-stoat' },
  'Sizzling Roast Venison': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-reddeer' },
  'Sizzling Roast Walrus': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-walrus' },
  'Sizzling Roast Wild Beef': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-aurochs' },
  'Sizzling Roast Wild Horse': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-wildhorse' },
  'Sizzling Roast Wild Mutton': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-wildgoat' },
  'Sizzling Roast Wildgoat': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-wildgoat' },// ????
  'Sizzling Roast Wolf': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-wolf' },
  'Sizzling Roast Wolverine': { res: 'gfx/invobjs/meat-roast', mod: 'gfx/invobjs/meat-wolverine' },

  'Spitroast Adder': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-adder' },
  'Spitroast Badger': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-badger' },
  'Spitroast Bat': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-bat' },
  'Spitroast Bear': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-bear' },
  'Spitroast Beaver': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-beaver' },
  'Spitroast Beef': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-cow' },
  'Spitroast Boar': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-boar' },
  'Spitroast Bog turtle': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-bogturtle' },
  'Spitroast Cachalot': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-spermwhale' },
  'Spitroast Caverat': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-caverat' },
  'Spitroast Fox': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-fox' },
  'Spitroast Goat': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-goat' },
  'Spitroast Grey Seal': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-greyseal' },
  'Spitroast Hedgehog': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-hedgehog' },
  'Spitroast Horse': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-horse' },
  'Spitroast Lynx': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-lynx' },
  'Spitroast Mammoth': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-mammoth' },
  'Spitroast Mole': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-mole' },
  'Spitroast Moose': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-moose' },
  'Spitroast Mutton': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-sheep' },
  'Spitroast Orca': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-orca' },
  'Spitroast Otter': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-otter' },
  'Spitroast Pork': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-pig' },
  'Spitroast Rabbit': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-rabbit' },
  'Spitroast Reindeer Venison': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-reindeer' },
  'Spitroast Squirrel': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-squirrel' },
  'Spitroast Stoat': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-stoat' },
  'Spitroast Venison': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-reddeer' },
  'Spitroast Walrus': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-walrus' },
  'Spitroast Wild Beef': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-aurochs' },
  'Spitroast Wild Horse': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-wildhorse' },
  'Spitroast Wild Mutton': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-wildgoat' },
  'Spitroast Wildgoat': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-wildgoat' },// ????
  'Spitroast Wolf': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-wolf' },
  'Spitroast Wolverine': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-wolverine' },

  'Sizzling Spitroast Adder': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-adder' },
  'Sizzling Spitroast Badger': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-badger' },
  'Sizzling Spitroast Bat': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-bat' },
  'Sizzling Spitroast Bear': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-bear' },
  'Sizzling Spitroast Beaver': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-beaver' },
  'Sizzling Spitroast Beef': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-cow' },
  'Sizzling Spitroast Boar': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-boar' },
  'Sizzling Spitroast Bog turtle': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-bogturtle' },
  'Sizzling Spitroast Cachalot': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-spermwhale' },
  'Sizzling Spitroast Caverat': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-caverat' },
  'Sizzling Spitroast Fox': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-fox' },
  'Sizzling Spitroast Goat': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-goat' },
  'Sizzling Spitroast Grey Seal': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-greyseal' },
  'Sizzling Spitroast Hedgehog': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-hedgehog' },
  'Sizzling Spitroast Horse': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-horse' },
  'Sizzling Spitroast Lynx': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-lynx' },
  'Sizzling Spitroast Mammoth': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-mammoth' },
  'Sizzling Spitroast Mole': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-mole' },
  'Sizzling Spitroast Moose': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-moose' },
  'Sizzling Spitroast Mutton': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-sheep' },
  'Sizzling Spitroast Orca': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-orca' },
  'Sizzling Spitroast Otter': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-otter' },
  'Sizzling Spitroast Pork': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-pig' },
  'Sizzling Spitroast Rabbit': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-rabbit' },
  'Sizzling Spitroast Reindeer Venison': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-reindeer' },
  'Sizzling Spitroast Squirrel': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-squirrel' },
  'Sizzling Spitroast Stoat': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-stoat' },
  'Sizzling Spitroast Venison': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-reddeer' },
  'Sizzling Spitroast Walrus': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-walrus' },
  'Sizzling Spitroast Wild Beef': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-aurochs' },
  'Sizzling Spitroast Wild Horse': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-wildhorse' },
  'Sizzling Spitroast Wild Mutton': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-wildgoat' },
  'Sizzling Spitroast Wildgoat': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-wildgoat' },// ????
  'Sizzling Spitroast Wolf': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-wolf' },
  'Sizzling Spitroast Wolverine': { res: 'gfx/invobjs/meat-spitroast', mod: 'gfx/invobjs/meat-wolverine' },

  'Chicken': { res: 'gfx/invobjs/meat-poultry', mod: 'gfx/invobjs/meat-chicken' },
  'Eagle Owl': { res: 'gfx/invobjs/meat-poultry', mod: 'gfx/invobjs/meat-eagleowl' },
  'Magpie': { res: 'gfx/invobjs/meat-poultry', mod: 'gfx/invobjs/meat-magpie' },
  'Mallard': { res: 'gfx/invobjs/meat-poultry', mod: 'gfx/invobjs/meat-mallard' },
  'Ptarmigan': { res: 'gfx/invobjs/meat-poultry', mod: 'gfx/invobjs/meat-ptarmigan' },
  'Quail': { res: 'gfx/invobjs/meat-poultry', mod: 'gfx/invobjs/meat-quail' },
  'Rock Dove': { res: 'gfx/invobjs/meat-poultry', mod: 'gfx/invobjs/meat-rockdove' },
  'Seagull': { res: 'gfx/invobjs/meat-poultry', mod: 'gfx/invobjs/meat-seagull' },
  'Swan': { res: 'gfx/invobjs/meat-poultry', mod: 'gfx/invobjs/meat-swan' },
  'Wood Grouse': { res: 'gfx/invobjs/meat-poultry', mod: 'gfx/invobjs/meat-woodgrouse' },

  'Roast Chicken': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-chicken' },
  'Roast Eagle Owl': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-eagleowl' },
  'Roast Magpie': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-magpie' },
  'Roast Mallard': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-mallard' },
  'Roast Ptarmigan': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-ptarmigan' },
  'Roast Quail': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-quail' },
  'Roast Rock Dove': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-rockdove' },
  'Roast Seagull': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-seagull' },
  'Roast Swan': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-swan' },
  'Roast Wood Grouse': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-woodgrouse' },

  'Sizzling Roast Chicken': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-chicken' },
  'Sizzling Roast Eagle Owl': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-eagleowl' },
  'Sizzling Roast Magpie': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-magpie' },
  'Sizzling Roast Mallard': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-mallard' },
  'Sizzling Roast Ptarmigan': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-ptarmigan' },
  'Sizzling Roast Quail': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-quail' },
  'Sizzling Roast Rock Dove': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-rockdove' },
  'Sizzling Roast Seagull': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-seagull' },
  'Sizzling Roast Swan': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-swan' },
  'Sizzling Roast Wood Grouse': { res: 'gfx/invobjs/meat-rpoultry', mod: 'gfx/invobjs/meat-woodgrouse' },

  'Spitroast Chicken': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-chicken' },
  'Spitroast Eagle Owl': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-eagleowl' },
  'Spitroast Magpie': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-magpie' },
  'Spitroast Mallard': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-mallard' },
  'Spitroast Ptarmigan': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-ptarmigan' },
  'Spitroast Quail': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-quail' },
  'Spitroast Rock Dove': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-rockdove' },
  'Spitroast Seagull': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-seagull' },
  'Spitroast Swan': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-swan' },
  'Spitroast Wood Grouse': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-woodgrouse' },

  'Sizzling Spitroast Chicken': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-chicken' },
  'Sizzling Spitroast Eagle Owl': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-eagleowl' },
  'Sizzling Spitroast Magpie': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-magpie' },
  'Sizzling Spitroast Mallard': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-mallard' },
  'Sizzling Spitroast Ptarmigan': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-ptarmigan' },
  'Sizzling Spitroast Quail': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-quail' },
  'Sizzling Spitroast Rock Dove': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-rockdove' },
  'Sizzling Spitroast Seagull': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-seagull' },
  'Sizzling Spitroast Swan': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-swan' },
  'Sizzling Spitroast Wood Grouse': { res: 'gfx/invobjs/meat-spoultry', mod: 'gfx/invobjs/meat-woodgrouse' },

  'Smoked Chicken': { res: 'gfx/invobjs/meat-kpoultry', mod: 'gfx/invobjs/meat-chicken' },
  'Smoked Eagle Owl': { res: 'gfx/invobjs/meat-kpoultry', mod: 'gfx/invobjs/meat-eagleowl' },
  'Smoked Magpie': { res: 'gfx/invobjs/meat-kpoultry', mod: 'gfx/invobjs/meat-magpie' },
  'Smoked Mallard': { res: 'gfx/invobjs/meat-kpoultry', mod: 'gfx/invobjs/meat-mallard' },
  'Smoked Ptarmigan': { res: 'gfx/invobjs/meat-kpoultry', mod: 'gfx/invobjs/meat-ptarmigan' },
  'Smoked Quail': { res: 'gfx/invobjs/meat-kpoultry', mod: 'gfx/invobjs/meat-quail' },
  'Smoked Rock Dove': { res: 'gfx/invobjs/meat-kpoultry', mod: 'gfx/invobjs/meat-rockdove' },
  'Smoked Seagull': { res: 'gfx/invobjs/meat-kpoultry', mod: 'gfx/invobjs/meat-seagull' },
  'Smoked Swan': { res: 'gfx/invobjs/meat-kpoultry', mod: 'gfx/invobjs/meat-swan' },
  'Smoked Wood Grouse': { res: 'gfx/invobjs/meat-kpoultry', mod: 'gfx/invobjs/meat-woodgrouse' },

  'Ant': { res: 'gfx/invobjs/meat-weird', mod: 'gfx/invobjs/meat-ant' },
  'Boreworm': { res: 'gfx/invobjs/meat-weird', mod: 'gfx/invobjs/meat-boreworm' },
  'Cave louse': { res: 'gfx/invobjs/meat-weird', mod: 'gfx/invobjs/meat-cavelouse' },
  'Troll': { res: 'gfx/invobjs/meat-weird', mod: 'gfx/invobjs/meat-troll' },

  'Smoked Ant': { res: 'gfx/invobjs/meat-kweird', mod: 'gfx/invobjs/meat-ant' },
  'Smoked Boreworm': { res: 'gfx/invobjs/meat-kweird', mod: 'gfx/invobjs/meat-boreworm' },
  'Smoked Cave louse': { res: 'gfx/invobjs/meat-kweird', mod: 'gfx/invobjs/meat-cavelouse' },
  'Smoked Troll': { res: 'gfx/invobjs/meat-kweird', mod: 'gfx/invobjs/meat-troll' },

  'Roast Ant': { res: 'gfx/invobjs/meat-rweird', mod: 'gfx/invobjs/meat-ant' },
  'Roast Boreworm': { res: 'gfx/invobjs/meat-rweird', mod: 'gfx/invobjs/meat-boreworm' },
  'Roast Cave louse': { res: 'gfx/invobjs/meat-rweird', mod: 'gfx/invobjs/meat-cavelouse' },
  'Roast Troll': { res: 'gfx/invobjs/meat-rweird', mod: 'gfx/invobjs/meat-troll' },

  'Sizzling Roast Ant': { res: 'gfx/invobjs/meat-rweird', mod: 'gfx/invobjs/meat-ant' },
  'Sizzling Roast Boreworm': { res: 'gfx/invobjs/meat-rweird', mod: 'gfx/invobjs/meat-boreworm' },
  'Sizzling Roast Cave louse': { res: 'gfx/invobjs/meat-rweird', mod: 'gfx/invobjs/meat-cavelouse' },
  'Sizzling Roast Troll': { res: 'gfx/invobjs/meat-rweird', mod: 'gfx/invobjs/meat-troll' },

  'Spitroast Ant': { res: 'gfx/invobjs/meat-sweird', mod: 'gfx/invobjs/meat-ant' },
  'Spitroast Boreworm': { res: 'gfx/invobjs/meat-sweird', mod: 'gfx/invobjs/meat-boreworm' },
  'Spitroast Cave louse': { res: 'gfx/invobjs/meat-sweird', mod: 'gfx/invobjs/meat-cavelouse' },
  'Spitroast Troll': { res: 'gfx/invobjs/meat-sweird', mod: 'gfx/invobjs/meat-troll' },

  'Sizzling Spitroast Ant': { res: 'gfx/invobjs/meat-sweird', mod: 'gfx/invobjs/meat-ant' },
  'Sizzling Spitroast Boreworm': { res: 'gfx/invobjs/meat-sweird', mod: 'gfx/invobjs/meat-boreworm' },
  'Sizzling Spitroast Cave louse': { res: 'gfx/invobjs/meat-sweird', mod: 'gfx/invobjs/meat-cavelouse' },
  'Sizzling Spitroast Troll': { res: 'gfx/invobjs/meat-sweird', mod: 'gfx/invobjs/meat-troll' },
  
  'Lobster': { res: 'gfx/invobjs/meat-crust', mod: 'gfx/invobjs/meat-lobster' },
  'Crab': { res: 'gfx/invobjs/meat-crust', mod: 'gfx/invobjs/meat-crab' },

  'Sizzling Lobster': { res: 'gfx/invobjs/meat-crustroast', mod: 'gfx/invobjs/meat-lobster' },
  'Sizzling Crab': { res: 'gfx/invobjs/meat-crustroast', mod: 'gfx/invobjs/meat-crab' },

  'Smoked Lobster': { res: 'gfx/invobjs/meat-crustsmoke', mod: 'gfx/invobjs/meat-lobster' },
  'Smoked Crab': { res: 'gfx/invobjs/meat-crustsmoke', mod: 'gfx/invobjs/meat-crab' },

  'Goat bollock': { res: 'gfx/invobjs/meat-testis', mod: 'gfx/invobjs/meat-goat' },
  'Beef bollock': { res: 'gfx/invobjs/meat-testis', mod: 'gfx/invobjs/meat-cow' },
  'Pork bollock': { res: 'gfx/invobjs/meat-testis', mod: 'gfx/invobjs/meat-pig' },
  'Horse bollock': { res: 'gfx/invobjs/meat-testis', mod: 'gfx/invobjs/meat-horse' },
  'Mutton bollock': { res: 'gfx/invobjs/meat-testis', mod: 'gfx/invobjs/meat-sheep' },


  'Aurochs Milk': { res: 'gfx/invobjs/milk', mod: 'gfx/invobjs/meat-aurochs' },
  'Goatsmilk': { res: 'gfx/invobjs/milk', mod: 'gfx/invobjs/meat-goat' },
  'Cowsmilk': { res: 'gfx/invobjs/milk', mod: 'gfx/invobjs/meat-cow' },
  'Sheepsmilk': { res: 'gfx/invobjs/milk', mod: 'gfx/invobjs/meat-sheep' },

  'Abyss Gazer': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-abyssgazer' },
  'Asp': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-asp' },
  'Bass': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-bass' },
  'Bream': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-bream' },
  'Brill': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-brill' },
  'Burbot': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-burbot' },
  'Carp': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-carp' },
  'Catfish': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-catfish' },
  'Cave Angler': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-caveangler' },
  'Cave Sculpin': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-cavesculpin' },
  'Cavelacanth': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-cavelacanth' },
  'Chub': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-chub' },
  'Cod': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-cod' },
  'Eel': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-eel' },
  'Grayling': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-grayling' },
  'Haddock': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-haddock' },
  'Herring': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-herring' },
  'Ide': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-ide' },
  'Lavaret': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-lavaret' },
  'Mackerel': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-mackerel' },
  'Mullet': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-mullet' },
  'Pale Ghostfish': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-paleghostfish' },
  'Perch': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-perch' },
  'Pike': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-pike' },
  'Plaice': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-plaice' },
  'Pomfret': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-pomfret' },
  'Roach': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-roach' },
  'Rose fish': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-rosefish' },
  'Ruffe': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-ruffe' },
  'Saithe': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-saithe' },
  'Salmon': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-salmon' },
  'Silver Bream': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-silverbream' },
  'Smelt': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-smelt' },
  'Sturgeon': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-sturgeon' },
  'Tench': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-tench' },
  'Trout': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-trout' },
  'Whiting': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-whiting' },
  'Zander': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-zander' },
  'Zope': { res: 'gfx/invobjs/meat-rfilet', mod: 'gfx/invobjs/meat-zope' },

  'Dried Filet of Abyss Gazer': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-abyssgazer' },
  'Dried Filet of Asp': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-asp' },
  'Dried Filet of Bass': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-bass' },
  'Dried Filet of Bream': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-bream' },
  'Dried Filet of Brill': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-brill' },
  'Dried Filet of Burbot': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-burbot' },
  'Dried Filet of Carp': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-carp' },
  'Dried Filet of Catfish': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-catfish' },
  'Dried Filet of Cave Angler': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-caveangler' },
  'Dried Filet of Cave Sculpin': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-cavesculpin' },
  'Dried Filet of Cavelacanth': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-cavelacanth' },
  'Dried Filet of Chub': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-chub' },
  'Dried Filet of Cod': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-cod' },
  'Dried Filet of Eel': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-eel' },
  'Dried Filet of Grayling': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-grayling' },
  'Dried Filet of Haddock': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-haddock' },
  'Dried Filet of Herring': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-herring' },
  'Dried Filet of Ide': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-ide' },
  'Dried Filet of Lavaret': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-lavaret' },
  'Dried Filet of Mackerel': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-mackerel' },
  'Dried Filet of Mullet': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-mullet' },
  'Dried Filet of Pale Ghostfish': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-paleghostfish' },
  'Dried Filet of Perch': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-perch' },
  'Dried Filet of Pike': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-pike' },
  'Dried Filet of Plaice': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-plaice' },
  'Dried Filet of Pomfret': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-pomfret' },
  'Dried Filet of Roach': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-roach' },
  'Dried Filet of Rose fish': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-rosefish' },
  'Dried Filet of Ruffe': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-ruffe' },
  'Dried Filet of Saithe': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-saithe' },
  'Dried Filet of Salmon': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-salmon' },
  'Dried Filet of Silver Bream': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-silverbream' },
  'Dried Filet of Smelt': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-smelt' },
  'Dried Filet of Sturgeon': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-sturgeon' },
  'Dried Filet of Tench': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-tench' },
  'Dried Filet of Trout': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-trout' },
  'Dried Filet of Whiting': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-whiting' },
  'Dried Filet of Zander': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-zander' },
  'Dried Filet of Zope': { res: 'gfx/invobjs/meat-dfilet', mod: 'gfx/invobjs/meat-zope' },

  'Spitroast Abyss Gazer': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-abyssgazer' },
  'Spitroast Asp': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-asp' },
  'Spitroast Bass': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-bass' },
  'Spitroast Bream': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-bream' },
  'Spitroast Brill': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-brill' },
  'Spitroast Burbot': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-burbot' },
  'Spitroast Carp': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-carp' },
  'Spitroast Catfish': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-catfish' },
  'Spitroast Cave Angler': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-caveangler' },
  'Spitroast Cave Sculpin': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-cavesculpin' },
  'Spitroast Cavelacanth': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-cavelacanth' },
  'Spitroast Chub': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-chub' },
  'Spitroast Cod': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-cod' },
  'Spitroast Eel': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-eel' },
  'Spitroast Grayling': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-grayling' },
  'Spitroast Haddock': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-haddock' },
  'Spitroast Herring': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-herring' },
  'Spitroast Ide': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-ide' },
  'Spitroast Lavaret': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-lavaret' },
  'Spitroast Mackerel': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-mackerel' },
  'Spitroast Mullet': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-mullet' },
  'Spitroast Pale Ghostfish': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-paleghostfish' },
  'Spitroast Perch': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-perch' },
  'Spitroast Pike': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-pike' },
  'Spitroast Plaice': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-plaice' },
  'Spitroast Pomfret': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-pomfret' },
  'Spitroast Roach': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-roach' },
  'Spitroast Rose fish': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-rosefish' },
  'Spitroast Ruffe': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-ruffe' },
  'Spitroast Saithe': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-saithe' },
  'Spitroast Salmon': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-salmon' },
  'Spitroast Silver Bream': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-silverbream' },
  'Spitroast Smelt': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-smelt' },
  'Spitroast Sturgeon': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-sturgeon' },
  'Spitroast Tench': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-tench' },
  'Spitroast Trout': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-trout' },
  'Spitroast Whiting': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-whiting' },
  'Spitroast Zander': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-zander' },
  'Spitroast Zope': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-zope' },

  'Sizzling Spitroast Abyss Gazer': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-abyssgazer' },
  'Sizzling Spitroast Asp': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-asp' },
  'Sizzling Spitroast Bass': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-bass' },
  'Sizzling Spitroast Bream': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-bream' },
  'Sizzling Spitroast Brill': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-brill' },
  'Sizzling Spitroast Burbot': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-burbot' },
  'Sizzling Spitroast Carp': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-carp' },
  'Sizzling Spitroast Catfish': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-catfish' },
  'Sizzling Spitroast Cave Angler': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-caveangler' },
  'Sizzling Spitroast Cave Sculpin': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-cavesculpin' },
  'Sizzling Spitroast Cavelacanth': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-cavelacanth' },
  'Sizzling Spitroast Chub': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-chub' },
  'Sizzling Spitroast Cod': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-cod' },
  'Sizzling Spitroast Eel': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-eel' },
  'Sizzling Spitroast Grayling': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-grayling' },
  'Sizzling Spitroast Haddock': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-haddock' },
  'Sizzling Spitroast Herring': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-herring' },
  'Sizzling Spitroast Ide': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-ide' },
  'Sizzling Spitroast Lavaret': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-lavaret' },
  'Sizzling Spitroast Mackerel': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-mackerel' },
  'Sizzling Spitroast Mullet': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-mullet' },
  'Sizzling Spitroast Pale Ghostfish': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-paleghostfish' },
  'Sizzling Spitroast Perch': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-perch' },
  'Sizzling Spitroast Pike': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-pike' },
  'Sizzling Spitroast Plaice': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-plaice' },
  'Sizzling Spitroast Pomfret': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-pomfret' },
  'Sizzling Spitroast Roach': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-roach' },
  'Sizzling Spitroast Rose fish': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-rosefish' },
  'Sizzling Spitroast Ruffe': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-ruffe' },
  'Sizzling Spitroast Saithe': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-saithe' },
  'Sizzling Spitroast Salmon': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-salmon' },
  'Sizzling Spitroast Silver Bream': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-silverbream' },
  'Sizzling Spitroast Smelt': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-smelt' },
  'Sizzling Spitroast Sturgeon': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-sturgeon' },
  'Sizzling Spitroast Tench': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-tench' },
  'Sizzling Spitroast Trout': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-trout' },
  'Sizzling Spitroast Whiting': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-whiting' },
  'Sizzling Spitroast Zander': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-zander' },
  'Sizzling Spitroast Zope': { res: 'gfx/invobjs/meat-sfilet', mod: 'gfx/invobjs/meat-zope' },

  'Smoked Abyss Gazer': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-abyssgazer' },
  'Smoked Asp': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-asp' },
  'Smoked Bass': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-bass' },
  'Smoked Bream': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-bream' },
  'Smoked Brill': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-brill' },
  'Smoked Burbot': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-burbot' },
  'Smoked Carp': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-carp' },
  'Smoked Catfish': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-catfish' },
  'Smoked Cave Angler': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-caveangler' },
  'Smoked Cave Sculpin': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-cavesculpin' },
  'Smoked Cavelacanth': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-cavelacanth' },
  'Smoked Chub': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-chub' },
  'Smoked Cod': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-cod' },
  'Smoked Eel': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-eel' },
  'Smoked Grayling': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-grayling' },
  'Smoked Haddock': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-haddock' },
  'Smoked Herring': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-herring' },
  'Smoked Ide': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-ide' },
  'Smoked Lavaret': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-lavaret' },
  'Smoked Mackerel': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-mackerel' },
  'Smoked Mullet': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-mullet' },
  'Smoked Pale Ghostfish': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-paleghostfish' },
  'Smoked Perch': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-perch' },
  'Smoked Pike': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-pike' },
  'Smoked Plaice': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-plaice' },
  'Smoked Pomfret': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-pomfret' },
  'Smoked Roach': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-roach' },
  'Smoked Rose fish': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-rosefish' },
  'Smoked Ruffe': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-ruffe' },
  'Smoked Saithe': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-saithe' },
  'Smoked Salmon': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-salmon' },
  'Smoked Silver Bream': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-silverbream' },
  'Smoked Smelt': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-smelt' },
  'Smoked Sturgeon': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-sturgeon' },
  'Smoked Tench': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-tench' },
  'Smoked Trout': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-trout' },
  'Smoked Whiting': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-whiting' },
  'Smoked Zander': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-zander' },
  'Smoked Zope': { res: 'gfx/invobjs/meat-kfilet', mod: 'gfx/invobjs/meat-zope' },

  'Abyss Gazer Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-abyssgazer' },
  'Asp Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-asp' },
  'Bass Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-bass' },
  'Bream Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-bream' },
  'Brill Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-brill' },
  'Burbot Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-burbot' },
  'Carp Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-carp' },
  'Catfish Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-catfish' },
  'Cave Angler Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-caveangler' },
  'Cave Sculpin Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-cavesculpin' },
  'Cavelacanth Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-cavelacanth' },
  'Chub Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-chub' },
  'Cod Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-cod' },
  'Eel Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-eel' },
  'Grayling Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-grayling' },
  'Haddock Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-haddock' },
  'Herring Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-herring' },
  'Ide Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-ide' },
  'Lavaret Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-lavaret' },
  'Mackerel Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-mackerel' },
  'Mullet Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-mullet' },
  'Pale Ghostfish Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-paleghostfish' },
  'Perch Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-perch' },
  'Pike Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-pike' },
  'Plaice Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-plaice' },
  'Pomfret Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-pomfret' },
  'Roach Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-roach' },
  'Rose fish Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-rosefish' },
  'Ruffe Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-ruffe' },
  'Saithe Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-saithe' },
  'Salmon Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-salmon' },
  'Silver Bream Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-silverbream' },
  'Smelt Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-smelt' },
  'Caviar': { res: 'gfx/invobjs/caviar', mod: 'gfx/invobjs/meat-sturgeon' },
  'Tench Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-tench' },
  'Trout Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-trout' },
  'Whiting Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-whiting' },
  'Zander Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-zander' },
  'Zope Roe': { res: 'gfx/invobjs/roe', mod: 'gfx/invobjs/meat-zope' },

  '': { res: '' },
};


fetch('https://hnhfood.vatsul.com/api/data/food-info2.json')
  .then(res => res.json())
  .then(data => {
    let recipes = data.filter(e => !(e.ingredients.filter(i => i.percentage !== 100 && i.percentage !== 200).length > 0));
    recipes.forEach(r => {
      let name = r.itemName;
      name = name === 'Magpie' ? 'Magpie (Pie)' : name;
      if (!name.match(/^([A-Z]|0\.50).+/g)) {
        return;
      }
      let food = allFood.filter(f => f.name === name)[0];
      if (!food) {
        food = {
          name: name,
          res: r.resourceName,
          recipes: []
        };
        allFood.push(food);
      }
      food.recipes.push({
        ingredients: r.ingredients.map(i => i.name),
        feps: r.feps,
        hunger: r.hunger,
        energy: r.energy
      });
    });
    allFood.sort((a, b) => a.name > b.name ? 1 : -1);
    allFood.forEach(f => {
      let path = './img/' + f.res + '.png';
      downloadFile('http://www.havenandhearth.com/mt/r/' + f.res, path);
    });
    Object.keys(resources).forEach(function (k) {
      let r = resources[k];
      let path = './img/' + r.res + '.png';
      downloadFile('http://www.havenandhearth.com/mt/r/' + r.res, path);
      if (r.mod) {
        path = './img/' + r.mod + '.png';
        downloadFile('http://www.havenandhearth.com/mt/r/' + r.mod, path);
      }
    });
  });

app.use(express.static('pages'));
app.use('/img/', express.static('img'));

app.get('/api/food', (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.json({ data: allFood });
});
app.get('/api/resources', (req, res) => {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.json({ data: resources });
});

const server = app.listen(port);
